# Generated by Django 3.1 on 2021-07-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
